#!/usr/bin/env python3
"""Process-independent owner of the D1 DDS writer and pose heartbeat.

The dashboard is only a Unix-socket client. Restarting Flask therefore cannot
close the DDS writer or interrupt the funcode-2 hold heartbeat.

CRITICAL — two failure modes we must avoid together:
1) Writer lock starvation: client publish never sleeps on the write path
   (dedicated writer thread + queue).
2) D1 command flood: Unitree documents mode0 @ ~10Hz for static data and
   mode1 for trajectories. Continuous mode1 at 20–100Hz (Caltech SURF + lab)
   overheats servos until the arm stops responding while hold_active stays true.

Heartbeat therefore rewrites poses as mode0, defaults to ~100ms, and is
suppressed while the client is already streaming funcode-2 motion.
"""

from __future__ import annotations

import argparse
from collections import deque
import json
import os
from pathlib import Path
import queue
import signal
import socketserver
import subprocess
import threading
import time
from typing import Any

try:
    import fcntl
except ImportError:  # Windows test host
    fcntl = None  # type: ignore[assignment]


def _boot_id() -> str:
    try:
        return Path("/proc/sys/kernel/random/boot_id").read_text(encoding="utf-8").strip()
    except OSError:
        return "unknown"


class HoldController:
    def __init__(
        self,
        *,
        command_bin: str,
        domain: int,
        command_delay_ms: int,
        heartbeat_ms: int,
        state_path: str,
        fake_log: str | None = None,
        hold_mode: int = 0,
    ) -> None:
        self.command_bin = command_bin
        self.domain = int(domain)
        self.command_delay_ms = int(command_delay_ms)
        # Floor 80ms: below ~10Hz we flood the D1 controller (doc + field reports).
        self.heartbeat_s = max(0.08, int(heartbeat_ms) / 1000.0)
        self.hold_mode = 0 if int(hold_mode) == 0 else 1
        self.state_path = Path(state_path)
        self.fake_log = Path(fake_log) if fake_log else None
        self.fake_publisher_alive = False
        self.lock = threading.RLock()
        self.proc: subprocess.Popen[str] | None = None
        self.publisher_generation = 0
        self.desired_coupled = False
        self.power_enabled = False
        self.last_pose: dict[str, Any] | None = None
        self.last_publish_mono = 0.0
        self.last_heartbeat_mono = 0.0
        self.last_client_pose_mono = 0.0
        self.heartbeat_count = 0
        self.event_seq = 0
        self.recent_events: deque[dict[str, Any]] = deque(maxlen=80)
        self.publisher_restart_count = 0
        self.last_error: str | None = None
        self.last_error_at: float | None = None
        self.started_mono = time.monotonic()
        self.stop_event = threading.Event()
        # Writer queue: heartbeat is generated by the writer itself so client
        # batches (and blocking stdin) cannot starve funcode-2.
        self._write_q: queue.Queue[tuple[str, Any] | None] = queue.Queue()
        self._load_same_boot_state()
        self.writer_thread = threading.Thread(target=self._writer_loop, name="d1-hold-writer", daemon=True)

    def start(self) -> None:
        self.writer_thread.start()

    def close(self) -> None:
        self.stop_event.set()
        try:
            self._write_q.put_nowait(None)
        except queue.Full:
            pass
        self.writer_thread.join(timeout=2.0)
        with self.lock:
            proc = self.proc
            self.proc = None
            self.fake_publisher_alive = False
            if proc is not None and proc.poll() is None:
                try:
                    if proc.stdin:
                        proc.stdin.close()
                    proc.wait(timeout=2.0)
                except (OSError, subprocess.TimeoutExpired):
                    proc.kill()

    def _load_same_boot_state(self) -> None:
        try:
            data = json.loads(self.state_path.read_text(encoding="utf-8"))
        except (OSError, ValueError, TypeError):
            return
        if data.get("boot_id") != _boot_id():
            return
        pose = data.get("last_pose")
        self.last_pose = dict(pose) if isinstance(pose, dict) else None
        self.desired_coupled = bool(data.get("desired_coupled")) and self.last_pose is not None
        self.power_enabled = bool(data.get("power_enabled"))

    def _save_state_locked(self) -> None:
        payload = {
            "boot_id": _boot_id(),
            "desired_coupled": self.desired_coupled,
            "power_enabled": self.power_enabled,
            "last_pose": self.last_pose,
            "saved_at": time.time(),
        }
        self.state_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.state_path.with_suffix(self.state_path.suffix + ".tmp")
        tmp.write_text(json.dumps(payload, separators=(",", ":")), encoding="utf-8")
        os.replace(tmp, self.state_path)

    def _publisher_alive_locked(self) -> bool:
        if self.fake_log is not None:
            return self.fake_publisher_alive
        return self.proc is not None and self.proc.poll() is None

    def _spawn_locked(self) -> bool:
        if self.fake_log is not None:
            self.fake_publisher_alive = True
            self.publisher_generation += 1
            if self.publisher_generation > 1:
                self.publisher_restart_count += 1
            return True
        try:
            self.proc = subprocess.Popen(
                [self.command_bin, str(self.domain), str(self.command_delay_ms)],
                stdin=subprocess.PIPE,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                text=True,
                bufsize=1,
                env=os.environ.copy(),
            )
        except OSError as exc:
            self.proc = None
            self._record_error_locked(f"publisher_spawn_failed:{exc!r}")
            return False
        time.sleep(0.18)
        if self.proc.poll() is not None:
            self.proc = None
            self._record_error_locked("publisher_exited_during_start")
            return False
        self.publisher_generation += 1
        if self.publisher_generation > 1:
            self.publisher_restart_count += 1
        return True

    def _record_error_locked(self, message: str) -> None:
        self.last_error = message
        self.last_error_at = time.time()
        self._record_event_locked(source="daemon", message={"funcode": -1, "data": {"event": message}}, ok=False)
        print(json.dumps({"level": "error", "event": message, "time": self.last_error_at}), flush=True)

    @staticmethod
    def _pose_servo_deg(message: dict[str, Any] | None) -> list[float] | None:
        data = message.get("data") if isinstance(message, dict) and isinstance(message.get("data"), dict) else None
        if not isinstance(data, dict):
            return None
        out: list[float] = []
        for index in range(7):
            key = f"angle{index}"
            if key not in data:
                return None
            try:
                out.append(round(float(data[key]), 3))
            except (TypeError, ValueError):
                return None
        return out

    def _record_event_locked(self, *, source: str, message: dict[str, Any], ok: bool = True) -> None:
        fc = int(message.get("funcode", -1))
        self.event_seq += 1
        event: dict[str, Any] = {
            "seq": self.event_seq,
            "source": source,
            "ok": bool(ok),
            "at": round(time.time(), 3),
            "mono_s": round(time.monotonic() - self.started_mono, 3),
            "funcode": fc,
            "desired_coupled": bool(self.desired_coupled),
        }
        pose = self._pose_servo_deg(message)
        if pose is not None:
            event["servo_deg"] = pose
        data = message.get("data") if isinstance(message.get("data"), dict) else {}
        if fc == 5:
            event["mode"] = data.get("mode")
        elif fc == 6:
            event["power"] = data.get("power")
        self.recent_events.append(event)

    def _raw_write_locked(self, message: dict[str, Any], *, source: str) -> bool:
        if self.fake_log is not None:
            self.fake_log.parent.mkdir(parents=True, exist_ok=True)
            with self.fake_log.open("a", encoding="utf-8") as stream:
                stream.write(json.dumps({"source": source, "message": message}, separators=(",", ":")) + "\n")
        else:
            if self.proc is None or self.proc.poll() is not None or self.proc.stdin is None:
                return False
            try:
                self.proc.stdin.write(json.dumps(message, separators=(",", ":")) + "\n")
                self.proc.stdin.flush()
            except (BrokenPipeError, OSError):
                return False
        self.last_publish_mono = time.monotonic()
        if source != "heartbeat" or self.heartbeat_count % 10 == 0:
            self._record_event_locked(source=source, message=message, ok=True)
        return True

    def _restore_hold_locked(self) -> bool:
        if not self.desired_coupled or self.last_pose is None:
            return True
        seq = int(time.time() * 1000) % 100000
        restore: list[dict[str, Any]] = []
        if self.power_enabled:
            restore.append({"seq": seq, "address": 1, "funcode": 6, "data": {"power": 1}})
            seq += 1
        restore.append({"seq": seq, "address": 1, "funcode": 5, "data": {"mode": 1}})
        hb = self._pose_for_heartbeat_locked()
        if hb is not None:
            restore.append(hb)
        return all(self._raw_write_locked(msg, source="restore") for msg in restore)

    def _ensure_publisher_locked(self) -> bool:
        if self._publisher_alive_locked():
            return True
        if not self._spawn_locked():
            return False
        return self._restore_hold_locked()

    def _apply_message_side_effects_locked(self, msg: dict[str, Any]) -> None:
        fc = int(msg.get("funcode", -1))
        data = msg.get("data") if isinstance(msg.get("data"), dict) else {}
        if fc == 6 and int(data.get("power", 0)) == 1:
            self.power_enabled = True
        elif fc == 5:
            self.desired_coupled = int(data.get("mode", 0)) == 1
            if not self.desired_coupled:
                self.last_pose = None
        elif fc == 2:
            self.last_pose = msg
            self.last_client_pose_mono = time.monotonic()

    def _pose_for_heartbeat_locked(self) -> dict[str, Any] | None:
        """Replay last angles as hold_mode (default 0), never trajectory mode1."""
        if self.last_pose is None:
            return None
        msg = dict(self.last_pose)
        data = dict(msg.get("data") or {}) if isinstance(msg.get("data"), dict) else {}
        data["mode"] = int(self.hold_mode)
        msg["data"] = data
        return msg

    def _client_motion_recent_locked(self) -> bool:
        """True while client is already streaming poses — skip duplicate heartbeat."""
        if self.last_client_pose_mono <= 0:
            return False
        grace = max(self.heartbeat_s * 1.5, 0.15)
        return (time.monotonic() - self.last_client_pose_mono) < grace

    def _emit_heartbeat_locked(self) -> None:
        if not self.desired_coupled or self.last_pose is None:
            return
        if self._client_motion_recent_locked():
            # Motion stream is the sole publisher; still mark freshness.
            self.last_heartbeat_mono = time.monotonic()
            return
        if not self._ensure_publisher_locked():
            return
        hb = self._pose_for_heartbeat_locked()
        if hb is None:
            return
        if self._raw_write_locked(hb, source="heartbeat"):
            self.last_heartbeat_mono = time.monotonic()
            self.heartbeat_count += 1

    def _writer_loop(self) -> None:
        """Owns all DDS writes. Heartbeat cannot be starved by client batches."""
        next_hb = time.monotonic()
        while not self.stop_event.is_set():
            timeout = max(0.001, next_hb - time.monotonic())
            try:
                item = self._write_q.get(timeout=timeout)
            except queue.Empty:
                item = ("heartbeat", None)
            if item is None or self.stop_event.is_set():
                break
            kind, payload = item
            if kind == "heartbeat":
                with self.lock:
                    self._emit_heartbeat_locked()
                next_hb = time.monotonic() + self.heartbeat_s
                continue
            if kind == "client_msg":
                msg, done_event, result_box = payload
                ok = False
                with self.lock:
                    if not self._ensure_publisher_locked():
                        result_box["ok"] = False
                        result_box["reason"] = "publisher_start_failed"
                    elif not self._raw_write_locked(dict(msg), source="client"):
                        self.proc = None
                        self._record_error_locked("publisher_write_failed")
                        result_box["ok"] = False
                        result_box["reason"] = "publisher_write_failed"
                    else:
                        self._apply_message_side_effects_locked(msg)
                        ok = True
                        result_box["ok"] = True
                if ok:
                    # Client motion traffic also refreshes hold freshness.
                    with self.lock:
                        if self.desired_coupled and self.last_pose is not None:
                            self.last_heartbeat_mono = time.monotonic()
                done_event.set()
                # Do NOT emit an extra heartbeat mid-batch: that doubles DDS flood
                # during trajectories. Only push the deadline forward.
                if time.monotonic() >= next_hb:
                    next_hb = time.monotonic() + self.heartbeat_s
                continue
            if kind == "save_state":
                with self.lock:
                    self._save_state_locked()
                continue

    def publish(self, messages: list[dict[str, Any]], *, delay_ms: int = 0) -> dict[str, Any]:
        if not messages:
            return {"ok": True, "count": 0, **self.status()}
        enables_couple = any(
            int(msg.get("funcode", -1)) == 5
            and isinstance(msg.get("data"), dict)
            and int(msg["data"].get("mode", 0)) == 1
            for msg in messages
        )
        supplies_pose = any(int(msg.get("funcode", -1)) == 2 for msg in messages)
        with self.lock:
            if enables_couple and self.last_pose is None and not supplies_pose:
                return {"ok": False, "reason": "couple_requires_pose", **self._status_locked()}
        sent = 0
        per_message_delay_s = min(0.5, max(0, int(delay_ms)) / 1000.0)
        for index, message in enumerate(messages):
            done = threading.Event()
            result: dict[str, Any] = {}
            self._write_q.put(("client_msg", (dict(message), done, result)))
            if not done.wait(timeout=8.0):
                return {"ok": False, "reason": "publisher_write_timeout", "count": sent, **self.status()}
            if not result.get("ok"):
                return {
                    "ok": False,
                    "reason": result.get("reason") or "publisher_write_failed",
                    "count": sent,
                    **self.status(),
                }
            sent += 1
            # Sleep OUTSIDE the writer path so heartbeat keeps running.
            if per_message_delay_s > 0 and index + 1 < len(messages):
                time.sleep(per_message_delay_s)
        self._write_q.put(("save_state", None))
        return {"ok": True, "count": sent, "stream": True, **self.status()}

    def _status_locked(self) -> dict[str, Any]:
        now = time.monotonic()
        publisher_alive = self._publisher_alive_locked()
        heartbeat_age_ms = None
        if self.last_heartbeat_mono > 0:
            heartbeat_age_ms = round((now - self.last_heartbeat_mono) * 1000.0, 1)
        publish_age_ms = None
        if self.last_publish_mono > 0:
            publish_age_ms = round((now - self.last_publish_mono) * 1000.0, 1)
        freshness_ms = heartbeat_age_ms if heartbeat_age_ms is not None else publish_age_ms
        hold_active = bool(
            publisher_alive
            and self.desired_coupled
            and self.last_pose is not None
            and freshness_ms is not None
            and freshness_ms <= max(350.0, self.heartbeat_s * 2500.0)
        )
        return {
            "protocol_version": 1,
            "daemon_pid": os.getpid(),
            "publisher_pid": self.proc.pid if self.proc is not None and self.proc.poll() is None else None,
            "publisher_alive": publisher_alive,
            "publisher_generation": self.publisher_generation,
            "publisher_restart_count": self.publisher_restart_count,
            "desired_coupled": self.desired_coupled,
            "hold_active": hold_active,
            "has_pose": self.last_pose is not None,
            "hold_target_servo_deg": self._pose_servo_deg(self.last_pose),
            "recent_events": list(self.recent_events)[-24:],
            "last_publish_age_ms": publish_age_ms,
            "heartbeat_age_ms": heartbeat_age_ms,
            "heartbeat_count": self.heartbeat_count,
            "heartbeat_period_ms": round(self.heartbeat_s * 1000.0, 1),
            "hold_mode": int(self.hold_mode),
            "client_motion_recent": self._client_motion_recent_locked(),
            "uptime_s": round(now - self.started_mono, 3),
            "last_error": self.last_error,
            "last_error_at": self.last_error_at,
            "writer_queue_depth": self._write_q.qsize(),
        }

    def status(self) -> dict[str, Any]:
        with self.lock:
            return {"ok": True, **self._status_locked()}


class HoldRequestHandler(socketserver.StreamRequestHandler):
    def handle(self) -> None:
        controller: HoldController = self.server.controller  # type: ignore[attr-defined]
        try:
            request = json.loads(self.rfile.readline(1024 * 1024).decode("utf-8"))
            action = request.get("action")
            if action == "status":
                response = controller.status()
            elif action == "publish":
                messages = request.get("messages")
                if not isinstance(messages, list) or not all(isinstance(x, dict) for x in messages):
                    response = {"ok": False, "reason": "invalid_messages"}
                else:
                    response = controller.publish(messages, delay_ms=int(request.get("delay_ms", 0)))
            else:
                response = {"ok": False, "reason": "invalid_action"}
        except (ValueError, UnicodeDecodeError) as exc:
            response = {"ok": False, "reason": "bad_request", "detail": repr(exc)}
        self.wfile.write((json.dumps(response, separators=(",", ":")) + "\n").encode("utf-8"))


_UnixStreamServerBase = getattr(socketserver, "UnixStreamServer", socketserver.TCPServer)


class HoldUnixServer(socketserver.ThreadingMixIn, _UnixStreamServerBase):
    daemon_threads = True
    allow_reuse_address = True


class HoldTcpServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
    daemon_threads = True
    allow_reuse_address = True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--socket", default=os.environ.get("D1_HOLD_SOCKET", "/tmp/go2_d1_hold.sock"))
    parser.add_argument("--state", default=os.environ.get("D1_HOLD_STATE", "/tmp/go2_d1_hold_state.json"))
    parser.add_argument("--lock", default=os.environ.get("D1_HOLD_LOCK", "/tmp/go2_d1_hold.lock"))
    parser.add_argument("--command-bin", default=os.environ.get("D1_SDK_COMMAND_BIN", "bin/d1_sdk_command"))
    parser.add_argument("--domain", type=int, default=int(os.environ.get("GO2_DDS_DOMAIN", "0")))
    parser.add_argument("--command-delay-ms", type=int, default=int(os.environ.get("D1_JOG_DAEMON_DELAY_MS", "0")))
    parser.add_argument(
        "--heartbeat-ms",
        type=int,
        default=int(os.environ.get("D1_HOLD_HEARTBEAT_MS", "100")),
        help="Hold keepalive period (ms). Unitree D1 cycle is ~10Hz; default 100.",
    )
    parser.add_argument(
        "--hold-mode",
        type=int,
        default=int(os.environ.get("D1_HOLD_MODE", "0")),
        help="funcode-2 mode for heartbeat (0=10Hz hold, 1=trajectory). Default 0.",
    )
    parser.add_argument("--fake-log", default=None, help=argparse.SUPPRESS)
    args = parser.parse_args()

    lock_stream = open(args.lock, "a+", encoding="utf-8")
    if fcntl is not None:
        try:
            fcntl.flock(lock_stream.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            print("D1_HOLD_DAEMON_ALREADY_RUNNING", flush=True)
            lock_stream.close()
            return 73

    tcp_endpoint = args.socket.startswith("tcp://")
    socket_path: Path | None = None
    if tcp_endpoint:
        host, port = args.socket[6:].rsplit(":", 1)
        server_address: Any = (host, int(port))
    else:
        socket_path = Path(args.socket)
        socket_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            socket_path.unlink()
        except FileNotFoundError:
            pass
        server_address = str(socket_path)
    controller = HoldController(
        command_bin=args.command_bin,
        domain=args.domain,
        command_delay_ms=args.command_delay_ms,
        heartbeat_ms=args.heartbeat_ms,
        state_path=args.state,
        fake_log=args.fake_log,
        hold_mode=args.hold_mode,
    )
    server = (HoldTcpServer if tcp_endpoint else HoldUnixServer)(server_address, HoldRequestHandler)
    server.controller = controller  # type: ignore[attr-defined]
    if socket_path is not None:
        os.chmod(socket_path, 0o660)
    stopping = threading.Event()

    def stop_server(_signum: int, _frame: Any) -> None:
        if not stopping.is_set():
            stopping.set()
            threading.Thread(target=server.shutdown, daemon=True).start()

    signal.signal(signal.SIGTERM, stop_server)
    signal.signal(signal.SIGINT, stop_server)
    controller.start()
    try:
        server.serve_forever(poll_interval=0.1)
    finally:
        server.server_close()
        controller.close()
        if socket_path is not None:
            try:
                socket_path.unlink()
            except FileNotFoundError:
                pass
        lock_stream.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
