#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parent.parent


class D1RgbAndMotorUiTests(unittest.TestCase):
    def test_nx_env_pins_color_nodes_not_depth_nodes(self) -> None:
        src = (ROOT / "scripts" / "nx_d1_jog_env.sh").read_text(encoding="utf-8", errors="replace")
        self.assertIn('D1_WRIST_V4L_INDEX="${D1_WRIST_V4L_INDEX:-4}"', src)
        self.assertIn('D1_FRONT_V4L_INDEX="${D1_FRONT_V4L_INDEX:-10}"', src)
        self.assertIn('D1_ORBBEC_RGB_V4L_INDEX="${D1_ORBBEC_RGB_V4L_INDEX:-4}"', src)
        self.assertIn('D1_ORBBEC_RELOAD_UVC="${D1_ORBBEC_RELOAD_UVC:-0}"', src)
        self.assertNotIn('D1_WRIST_V4L_INDEX="${D1_WRIST_V4L_INDEX:-2}"', src)
        self.assertNotIn('D1_FRONT_V4L_INDEX="${D1_FRONT_V4L_INDEX:-8}"', src)

    def test_app_resolves_both_realsense_color_interfaces(self) -> None:
        src = (ROOT / "go2_dashboard" / "d1_jog" / "app.py").read_text(encoding="utf-8", errors="replace")
        self.assertIn('"D1_WRIST_V4L_INDEX", "0b5c", 4', src)
        self.assertIn('"D1_FRONT_V4L_INDEX", "0b3a", 10', src)
        self.assertIn('return ":1.3" in device_path and stream_index == 0', src)
        self.assertIn('"detection_source": "wrist"', src)
        self.assertIn('for i in range(12):', src)
        self.assertIn('move_to_servo_deg_smooth(target)', src)
        self.assertIn('out["sport_probe"] = invoke_dds_sport_ping()', src)
        self.assertIn('@app.route("/assets/<string:name>")', src)

    def test_ui_has_rgb_badges_and_full_motor_panel(self) -> None:
        src = (ROOT / "templates" / "d1_jog_dashboard.html").read_text(encoding="utf-8", errors="replace")
        self.assertIn('id="wristRgbBadge"', src)
        self.assertIn('id="frontRgbBadge"', src)
        self.assertIn('src="/motors"', src)
        self.assertIn('Unitree', src)
        self.assertIn('id="loadingScreen"', src)
        self.assertIn('id="diagJson"', src)
        self.assertIn('id="scanResult"', src)
        self.assertIn('id="scanPreview"', src)
        self.assertIn("function renderScanResult(payload)", src)
        self.assertIn('/assets/unitree_go2_hero.png', src)
        self.assertEqual(src.count('data-teach-section='), 4)
        self.assertIn('data-teach-section="cameras"', src)
        self.assertIn('data-teach-section="control"', src)
        self.assertIn('data-teach-section="grasp2d"', src)
        self.assertIn('data-teach-section="grasp6d"', src)
        self.assertIn('id="btnArmCouple"', src)
        self.assertIn('id="btnModeCalib"', src)
        self.assertIn('id="btnModePick"', src)
        self.assertIn('id="btnTeachRelease"', src)
        self.assertIn('id="btnTeachCapture"', src)
        self.assertIn('Memorizza + HOLD', src)
        self.assertIn("'/api/pick/teach/finish'", src)
        self.assertIn('id="btnTeachScanScenario"', src)
        self.assertIn('id="btnTeachReset"', src)
        self.assertIn('id="teachCoverage"', src)
        self.assertIn('require_valid_vision: true', src)
        self.assertIn("vision_mode: '2d'", src)
        self.assertIn('Scansione fresca + presa 2D', src)
        self.assertIn('id="btnDepthStart"', src)
        self.assertIn('id="btnLowerHeight"', src)
        self.assertIn('id="btnLowerCluster"', src)
        self.assertIn('id="btnLowerDimension"', src)
        self.assertIn('id="poseJ0"', src)
        self.assertIn('id="poseJ6"', src)
        self.assertIn('id="btnReadPoseSliders"', src)
        self.assertIn('id="btnSendPoseSliders"', src)
        self.assertIn("'/api/joints/jog'", src)
        self.assertIn('with_enable: true', src)
        self.assertNotIn('data-micro-joint', src)
        self.assertNotIn('micro-jog', src)
        self.assertIn('id="btn6dCalibRelease"', src)
        self.assertIn('4. Salva sample + HOLD', src)
        self.assertIn('id="calibGuide"', src)
        self.assertIn('Nuova calibrazione 6D', src)
        self.assertIn('/api/pick/metric/calibration/target.pdf', src)
        self.assertIn('function activateArmControl()', src)
        self.assertIn('function setUiMode(mode)', src)
        self.assertIn('function setAutoMotionUi(enabled)', src)
        self.assertIn('id="calibHistory"', src)
        self.assertIn('0% · 0 / 8', src)
        self.assertIn('id="btn6dCalibLive"', src)
        self.assertIn('id="btn6dAutoCalib"', src)
        self.assertIn('id="btn6dAutoCalibTop"', src)
        self.assertIn('id="btn6dAutoCalibStop"', src)
        self.assertIn('AUTO CALIBRAZIONE 6D', src)
        self.assertIn('D1_GRASP6D_AUTO_MOTION_ENABLE', src)
        self.assertIn('id="autoCalibDebugGraph"', src)
        self.assertIn('function renderAutoCalibrationDebug()', src)
        self.assertIn('auto-step-pill', src)
        self.assertIn('Auto bloccata', src)
        self.assertIn('Riprendere AUTO calibrazione 6D', src)
        self.assertIn("autoCalibStep = existingSamples", src)
        self.assertIn('preset scan SX', src)
        self.assertNotIn('base_servo_deg: autoCalibBase', src)
        self.assertIn('Auto calibrazione 6D', src)
        self.assertIn("'/api/pick/metric/calibration/auto_step'", src)
        self.assertIn("confirm: 'AUTO_CALIBRATE_6D'", src)
        self.assertIn('id="calibPhaseFlow"', src)
        self.assertIn('id="calibSaveGate"', src)
        self.assertIn('function updateCalibrationPokaYoke()', src)
        self.assertIn('calibrationSaveAllowed', src)
        self.assertIn('Salvataggio bloccato', src)
        self.assertIn('Passo attuale: attiva il controllo, poi calibra', src)
        self.assertIn('1. Nuova calibrazione 6D', src)
        self.assertIn('2. Avvia guida live', src)
        self.assertIn('3. Release: lo sostengo io', src)
        self.assertIn('4. Salva sample + HOLD', src)
        self.assertIn('5. Calcola hand-eye 6D', src)
        self.assertIn('Verifica AprilGrid (diagnosi)', src)
        self.assertIn('id="calibResidualState"', src)
        self.assertIn('id="calibDebugGraph"', src)
        self.assertIn('function renderCalibrationDebugGraph(quality)', src)
        self.assertIn('Sessione incoerente: rifai pulito', src)
        self.assertIn('Trend residuo', src)
        self.assertIn('MIGLIORA RESIDUO', src)
        self.assertIn('NON SALVARE · peggiora', src)
        self.assertIn('NON SALVARE · solo centri', src)
        self.assertIn('tag_corners', src)
        self.assertNotIn('BUONA VISTA', src)
        self.assertIn('POINT CLOUD', (ROOT / "go2_dashboard" / "d1_jog" / "app.py").read_text(encoding="utf-8"))
        self.assertIn('window.confirm(', src)
        self.assertIn("{ confirm: 'RELEASE_ARM_TORQUE' }", src)
        self.assertNotIn('id="btnSavePickTuning"', src)
        self.assertNotIn('id="btnSaveGraspParams"', src)
        self.assertNotIn('Tuning avanzato presa', src)
        self.assertNotIn('Parametri calibrazione presa', src)
        self.assertNotIn('Taratura posizione robot con Slider', src)
        self.assertNotIn('Pose rapide e programmi', src)
        self.assertNotIn('Presa legacy (2D scan)', src)
        self.assertNotIn('id="heroCardA"', src)
        self.assertNotIn('}, 45000);', src)

    def test_historical_motor_modules_are_present(self) -> None:
        for rel in (
            "go2_dashboard/motor_health_app.py",
            "go2_dashboard/go2_motor_health.py",
            "go2_dashboard/go2_motor_event_log.py",
            "go2_dashboard/go2_motor_sport.py",
            "go2_dashboard/go2_thermal_protect.py",
            "go2_dashboard/go2_thermal_settings.py",
        ):
            self.assertTrue((ROOT / rel).is_file(), rel)

    def test_arm_runtime_and_daemon_regressions_are_guarded(self) -> None:
        env = (ROOT / "scripts" / "nx_d1_jog_env.sh").read_text(encoding="utf-8", errors="replace")
        service = (ROOT / "go2_dashboard" / "d1_jog" / "service.py").read_text(
            encoding="utf-8", errors="replace"
        )
        self.assertEqual(env.count("D1_JOG_ENABLE_EVERY_TICKS="), 1)
        self.assertIn("D1_JOG_ENABLE_EVERY_TICKS=0", env)
        self.assertEqual(env.count("D1_ORBBEC_RGB_ONLY="), 1)
        self.assertIn("sdk_reinstall_backup_19700225_160102", env)
        self.assertIn("unset LD_PRELOAD", env)
        self.assertIn("def command_daemon_status()", service)
        self.assertIn('"daemon_died_after_publish"', service)
        self.assertIn("_recent_publishes", service)
        self.assertIn('"last_pose_target_servo_deg"', service)
        self.assertIn("tracking_error_too_high", (ROOT / "go2_dashboard" / "d1_jog" / "program_runner.py").read_text(
            encoding="utf-8", errors="replace"
        ))
        self.assertIn("D1_PROG_TRACKING_DURING_MOVE", (ROOT / "go2_dashboard" / "d1_jog" / "program_runner.py").read_text(
            encoding="utf-8", errors="replace"
        ))
        self.assertIn("D1_PROG_TRACKING_MAX_VIOLATIONS", (ROOT / "go2_dashboard" / "d1_jog" / "program_runner.py").read_text(
            encoding="utf-8", errors="replace"
        ))
        self.assertIn("settle_tracking_error_too_high", (ROOT / "go2_dashboard" / "d1_jog" / "program_runner.py").read_text(
            encoding="utf-8", errors="replace"
        ))
        self.assertIn("settle_tracking_error_too_high", (ROOT / "go2_dashboard" / "d1_jog" / "program_runner.py").read_text(
            encoding="utf-8", errors="replace"
        ))
        self.assertIn("def couple_and_hold_pose(", service)
        self.assertIn('out["atomic_batch"] = True', service)
        self.assertIn("power_pose_couple_pose", service)
        self.assertNotIn("arm_keeper", service)
        self.assertIn("ensure_coupled(with_power=False, force=False)", service)
        self.assertNotIn("ensure_coupled(with_power=True, force=True)", service)
        self.assertIn("def request_emergency_hold(", service)
        self.assertIn("_parse_arm_feedback_stdout", service)
        self.assertIn('"arm_feedback_count"', service)
        self.assertIn("def safe_zero_pose_from_servo(", service)
        self.assertIn('D1_ZERO_TRANSIT_J1_DEG", "-90"', service)
        self.assertIn("d1_hold_client.external_hold_enabled()", service)
        self.assertIn('"continuous_hold_active"', service)
        self.assertIn('TRUE_ZERO_POSE_PATH = PROJECT_ROOT / "data" / "true_zero_pose.json"', service)
        hold_daemon = (ROOT / "scripts" / "d1_hold_daemon.py").read_text(
            encoding="utf-8", errors="replace"
        )
        self.assertIn('"hold_target_servo_deg"', hold_daemon)
        self.assertIn('"recent_events"', hold_daemon)
        app = (ROOT / "go2_dashboard" / "d1_jog" / "app.py").read_text(
            encoding="utf-8", errors="replace"
        )
        self.assertIn('body.get("confirm") != "RELEASE_ARM_TORQUE"', app)
        self.assertIn('"explicit_release_confirmation_required"', app)
        self.assertIn('@app.route("/api/joints/hold_now"', app)
        self.assertIn('@app.route("/api/arm/true_zero"', app)
        self.assertIn('@app.route("/api/programs/<program_id>/teach_capture"', app)
        self.assertIn('service.couple_and_hold_pose(taught, with_power=True, force=True)', app)
        self.assertIn('service.safe_zero_pose_from_servo', app)
        self.assertIn('side_transit[0] = float(target[0])', app)
        self.assertIn('"rotate_while_folded"', app)
        self.assertIn('"safe_transit_unavailable"', app)
        self.assertIn('def _legacy_scan_and_detect()', app)
        self.assertIn('"guided_2d_calibration_incomplete"', app)
        self.assertIn('"hold_target_error_deg"', app)
        self.assertIn('"arm_feedback"', app)
        self.assertIn("D1_GRASP6D_AUTO_TRACKING_MAX_ERR_DEG", app)
        self.assertIn('D1_GRASP6D_AUTO_TRACKING_MAX_ERR_DEG", "15"', app)
        self.assertIn("already_holding_soft_path", app)
        self.assertIn("auto_soft", app)
        self.assertIn("pose_mode=auto_pose_mode", app)
        self.assertIn("auto_base_current_pose", app)
        self.assertIn("start_far_from_scan_left_using_current", app)
        self.assertIn("auto_step_finally_measured_soft", app)
        self.assertIn("program_wait_at_target_failed", (ROOT / "go2_dashboard" / "d1_jog" / "program_runner.py").read_text(encoding="utf-8", errors="replace"))
        env = (ROOT / "scripts" / "nx_d1_jog_env.sh").read_text(encoding="utf-8", errors="replace")
        self.assertIn('D1_GRASP6D_AUTO_MOTION_ENABLE="${D1_GRASP6D_AUTO_MOTION_ENABLE:-1}"', env)
        self.assertIn('D1_GRASP6D_AUTO_MOVE_MODE="${D1_GRASP6D_AUTO_MOVE_MODE:-1}"', env)
        self.assertIn('D1_GRASP6D_AUTO_WAYPOINT_DELAY_MS="${D1_GRASP6D_AUTO_WAYPOINT_DELAY_MS:-220}"', env)
        self.assertIn('D1_GRASP6D_AUTO_JOINT_STEP_DEG="${D1_GRASP6D_AUTO_JOINT_STEP_DEG:-1.5}"', env)
        self.assertIn('D1_GRASP6D_AUTO_REST_S="${D1_GRASP6D_AUTO_REST_S:-1.2}"', env)
        self.assertIn('D1_GRASP6D_AUTO_SETTLE_S="${D1_GRASP6D_AUTO_SETTLE_S:-2.0}"', env)
        self.assertIn('D1_HOLD_HEARTBEAT_MS="${D1_HOLD_HEARTBEAT_MS:-100}"', env)
        self.assertIn('D1_HOLD_MODE="${D1_HOLD_MODE:-0}"', env)
        hold_daemon_src = (ROOT / "scripts" / "d1_hold_daemon.py").read_text(encoding="utf-8", errors="replace")
        self.assertIn("writer_queue_depth", hold_daemon_src)
        self.assertIn("_pose_for_heartbeat_locked", hold_daemon_src)
        self.assertIn("_client_motion_recent_locked", hold_daemon_src)
        self.assertIn('default=int(os.environ.get("D1_HOLD_HEARTBEAT_MS", "100"))', hold_daemon_src)
        motion_profile = (ROOT / "go2_dashboard" / "d1_jog" / "motion_profile.py").read_text(
            encoding="utf-8", errors="replace"
        )
        self.assertIn("hold_mode", motion_profile)
        self.assertIn("soft hold", motion_profile)
        self.assertIn("def soft_hold_measured", service)
        self.assertIn("def _hard_hold_reason", service)
        self.assertIn("hard: bool | None = None", service)
        self.assertIn("request_emergency_hold(reason=reason, hard=True)", app)
        runner = (ROOT / "go2_dashboard" / "d1_jog" / "program_runner.py").read_text(
            encoding="utf-8", errors="replace"
        )
        self.assertIn("held_measured", runner)
        self.assertIn("measured_feedback_soft", runner)
        self.assertIn("D1_GRASP6D_AUTO_TRACKING_MAX_ERR_DEG", env)
        self.assertIn("D1_GRASP6D_AUTO_MAX_START_DELTA_DEG", env)
        self.assertIn("D1_GRASP6D_AUTO_MOTION_ENABLE", app)
        self.assertIn("auto_motion_disabled_until_command_flow_stable", app)
        self.assertIn("_auto_calibration_base_pose", app)
        self.assertIn("_select_auto_calibration_offset", app)
        self.assertIn("reprojection_too_high", app)
        self.assertIn("median_frames", app)
        self.assertIn('_scan_side_target("left")', app)
        self.assertIn('"base_source": base_source', app)
        self.assertIn("auto_calibration_settle_tracking_error", app)
        self.assertIn("auto_watchdog_stop", app)
        self.assertIn("auto_motion_failed", app)
        self.assertIn('@app.route("/api/pick/metric/calibration/auto_step"', app)
        self.assertIn('@app.route("/api/pick/metric/calibration/auto_progress"', app)
        self.assertIn("_set_auto_progress", app)
        self.assertIn('"explicit_auto_calibration_confirmation_required"', app)
        self.assertIn('D1_GRASP6D_AUTO_MAX_DELTA_DEG', app)
        self.assertIn("build_ok_after_auto_prune", app)
        self.assertIn("build_ok_after_max_samples_prune", app)
        self.assertIn("len(samples) >= max_samples", app)
        self.assertIn("AUTO_STUCK_OFFSET_SCALE", env)
        self.assertIn("D1_GRASP6D_AUTO_MAX_REPROJ_PX", env)
        self.assertIn("D1_GRASP6D_AUTO_MEDIAN_FRAMES", env)
        self.assertIn('D1_GRASP6D_AUTO_MIN_VISIBLE_TAGS="${D1_GRASP6D_AUTO_MIN_VISIBLE_TAGS:-12}"', env)
        self.assertIn('D1_GRASP6D_CALIB_MIN_NEW_TRANSLATION_M="${D1_GRASP6D_CALIB_MIN_NEW_TRANSLATION_M:-0.04}"', env)
        html = (ROOT / "templates" / "d1_jog_dashboard.html").read_text(encoding="utf-8", errors="replace")
        self.assertIn("max_samples: 16", html)
        self.assertIn("softContinueReasons", html)
        self.assertIn("d.build && d.build.ok", html)
        self.assertIn("autoLivePanel", html)
        self.assertIn("pollAutoCalibrationProgress", html)
        self.assertIn("renderAutoLiveProgress", html)
        self.assertIn("pickDebugPanel", html)
        self.assertIn("btnPickDebugLive", html)
        grasp6d = (ROOT / "go2_dashboard" / "d1_jog" / "grasp6d.py").read_text(encoding="utf-8", errors="replace")
        self.assertIn("def prune_handeye_outliers", grasp6d)
        self.assertIn("def calib_min_samples", grasp6d)
        self.assertIn("prune_and_aggiungi_sample", grasp6d)
        self.assertIn("def _safe_inv4", grasp6d)
        self.assertIn("handeye_linalg_error", grasp6d)
        self.assertIn("singular_sample_transform", grasp6d)
        self.assertIn('@app.route("/api/pick/metric/calibration/prune"', app)
        self.assertIn("too_few_visible_tags", app)
        self.assertIn('D1_GRASP6D_CALIB_MAX_RMS_M="${D1_GRASP6D_CALIB_MAX_RMS_M:-0.025}"', env)
        self.assertIn('D1_GRASP6D_CALIB_MIN_SAMPLES="${D1_GRASP6D_CALIB_MIN_SAMPLES:-6}"', env)
        self.assertIn("pose_mode=auto_pose_mode", app)
        self.assertIn("max_step_deg=auto_step_deg", app)
        self.assertIn("min_delay_ms=auto_min_delay", app)
        jog_stream = (ROOT / "go2_dashboard" / "d1_jog" / "jog_stream.py").read_text(
            encoding="utf-8", errors="replace"
        )
        self.assertNotIn("publish_messages_stream(msgs", jog_stream)
        start = (ROOT / "scripts" / "nx_start_d1_jog.sh").read_text(encoding="utf-8", errors="replace")
        self.assertIn("D1_GRASP6D_AUTO_MOTION_ENABLE", env)
        self.assertIn("command_daemon", start)
        self.assertIn("startup_arm_stabilization", start)
        self.assertIn("nx_start_d1_hold_daemon.sh", start)
        self.assertIn("hold_active", start)
        self.assertTrue((ROOT / "scripts" / "verify_d1_arm_stack.py").is_file())

    def test_d1_boot_autostart_assets_are_present(self) -> None:
        deploy = (ROOT / "scripts" / "deploy_d1_jog_to_nx.py").read_text(encoding="utf-8", errors="replace")
        boot = (ROOT / "scripts" / "nx_boot_d1_jog_wrapper.sh").read_text(encoding="utf-8", errors="replace")
        svc = (ROOT / "scripts" / "go2-d1-jog-dashboard.service").read_text(encoding="utf-8", errors="replace")
        fg = (ROOT / "scripts" / "nx_serve_foreground_d1_jog.sh").read_text(
            encoding="utf-8", errors="replace"
        )
        self.assertIn("scripts/nx_boot_d1_jog_wrapper.sh", deploy)
        self.assertIn("scripts/go2-d1-jog-dashboard.service", deploy)
        self.assertIn("_remote_install_d1_crontab", deploy)
        self.assertIn("_remote_install_d1_systemd_user_optional", deploy)
        self.assertIn("_remote_remove_legacy_5052_autostart", deploy)
        self.assertIn("GO2_D1_JOG_RESTART", deploy)
        self.assertIn("GO2_D1_CONFIRM_ARM_SUPPORTED", deploy)
        self.assertIn("FILES-ONLY", deploy)
        self.assertIn("EXTERNAL_HOLD_PROCESS_ALIVE_REFUSE_KILL", deploy)
        self.assertIn("GO2_DASHBOARD_AUTOSTART", deploy)
        self.assertIn("nx_boot_dashboard_wrapper.sh", deploy)
        self.assertIn("GO2_D1_JOG_AUTOSTART", boot)
        self.assertIn("bash scripts/nx_start_d1_jog.sh", boot)
        self.assertIn("ExecStart=/home/unitree/go2_visual_dashboard/scripts/nx_serve_foreground_d1_jog.sh", svc)
        self.assertIn("source /home/unitree/go2_visual_dashboard/scripts/nx_d1_jog_env.sh", fg)
        self.assertIn("serve_d1_jog_dashboard.py", fg)

    def test_hermes_is_integrated_on_5056(self) -> None:
        app = (ROOT / "go2_dashboard" / "d1_jog" / "app.py").read_text(encoding="utf-8", errors="replace")
        ui = (ROOT / "templates" / "d1_jog_dashboard.html").read_text(encoding="utf-8", errors="replace")
        context = (ROOT / "go2_dashboard" / "hermes" / "context.py").read_text(
            encoding="utf-8", errors="replace"
        )
        self.assertIn('app.register_blueprint(hermes_bp)', app)
        self.assertIn('id="tabHermesBtn"', ui)
        self.assertIn('data-src="/focus/hermes"', ui)
        self.assertIn("http://127.0.0.1:5056", context)
        self.assertIn('integrato nello stesso processo e sulla stessa porta 5056', ui)
        hermes_html = (ROOT / "templates" / "hermes.html").read_text(encoding="utf-8")
        hermes_css = (ROOT / "static" / "hermes" / "hermes.css").read_text(encoding="utf-8")
        hermes_js = (ROOT / "static" / "hermes" / "hermes.js").read_text(encoding="utf-8")
        self.assertIn('/static/hermes/hermes.css', hermes_html)
        self.assertIn('.msn-window', hermes_css)
        self.assertIn('integrato nella dashboard 5056', hermes_js)


if __name__ == "__main__":
    unittest.main()
